version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playersdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - players-network

  app:
    image: maven:3.8.1-openjdk-17
    container_name: players-app
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: |
        bash -c "
            mvn clean package -DskipTests &&
            java -jar target/*.jar
        "
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/playersdatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - players-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - players-network

networks:
  players-network: