spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: GamerPool

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
  sql:
    init:
      mode: always
      data-locations: classpath:database/data.sql
      # schema-locations: classpath:database/schema.sql


#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      # http://localhost:8080/actuator
#      exposure:
#        include: [ "health","prometheus", "metrics" ]
#  endpoint:
#    health:
#      show-details: always
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs


logging:
  level:
    root: INFO
