spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/players
    username: postgres
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
server:
  port: 8090

logging:
  level:
    root: INFO